# Generated by Django 3.0.5 on 2020-04-02 18:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200402_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbs_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_saturated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.uuid_upload_to),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.uuid_upload_to),
        ),
    ]
