# Generated by Django 3.0.5 on 2020-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200402_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
