# Generated by Django 3.0.5 on 2020-04-28 13:36

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200425_1616'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', core.models.MyUserManager()),
            ],
        ),
    ]
