# Generated by Django 3.0.5 on 2020-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200428_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
