# Generated by Django 3.0.5 on 2020-04-29 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_myuser_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('reference', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
