# Generated by Django 3.0.5 on 2020-04-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_token_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['-step']},
        ),
    ]
