# Generated by Django 3.0.5 on 2020-04-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_orderingOnStep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['step']},
        ),
    ]
