# Generated by Django 3.0.5 on 2020-05-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200430_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient__name']},
        ),
    ]
