# Generated by Django 3.0.5 on 2020-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200508_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipestep',
            unique_together=set(),
        ),
    ]
